[global]
developmentMode = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
backgroundColor = "#FAF8F3"
